# https://github.com/yeasy/docker-compose-files/tree/master/hyperledger
# This compose file will start a Hyperledger Fabric 1.0 MVE, including
# * 0 ca
# * 1 orderer
# * 2 peers in 2 orgs
# * cli for testing

version: '3.0'

services:
  orderer.example.com:  # There  can be multiple orderers
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_LEDGERTYPE=file
      - ORDERER_GENERAL_BATCHTIMEOUT=2s
      - ORDERER_GENERAL_MAXMESSAGECOUNT=10
      - ORDERER_GENERAL_MAXWINDOWSIZE=1000
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_TLS_ENABLED=false
    expose:
      - "7050"  #
    container_name: orderer
    hostname: orderer
    ports:
      - "7050:7050"
    volumes:
    - ./e2e_cli/channel-artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./e2e_cli/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    command: orderer start

  peer0.org1.example.com:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0_org1
      - CORE_PEER_ADDRESS=peer0_org1:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0_org1:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0_org1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=10_default  
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false  # this node is the group leader, default to false
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_ENABLED=false
    expose:
      - "7050"  # Rest
      - "7051"  # Grpc
      - "7052"  # Peer CLI
      - "7053"  # Peer Event
      - "7054"  # eCAP
      - "7055"  # eCAA
      - "7056"  # tCAP
      - "7057"  # eCAA
      - "7058"  # tlsCAP
      - "7059"  # tlsCAA
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
    #volumes:
    #    - /var/run/:/host/var/run/
    container_name: peer0_org1
    hostname: peer0_org1
    volumes:
        - ./e2e_cli/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    command: peer node start

  peer0.org2.example.com:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0_org2
      - CORE_PEER_ADDRESS=peer0_org2:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0_org2:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0_org2:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0_org2:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=10_default  # uncomment this to use specific network
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false  # this node is the group leader, default to false
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_ENABLED=false
    expose:
      - "7050"  # Rest
      - "7051"  # Grpc
      - "7052"  # Peer CLI
      - "7053"  # Peer Event
      - "7054"  # eCAP
      - "7055"  # eCAA
      - "7056"  # tCAP
      - "7057"  # eCAA
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
    #volumes:
    #    - /var/run/:/host/var/run/
    container_name: peer0_org2
    hostname: peer0_org2
    volumes:
        - ./e2e_cli/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053
    command: peer node start

  cli:
    container_name: fabric-cli
    hostname: fabric-cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      #- GOPATH=/opt/gopath
      - CORE_PEER_ID=fabric-cli
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ADDRESS=peer0_org1:7051 # default to operate on peer0.org1
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false  
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    volumes:
        - ./e2e_cli/examples:/opt/gopath/src/github.com/hyperledger/fabric/examples
        - ./e2e_cli/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./e2e_cli/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./e2e_cli/configtx.yaml:/etc/hyperledger/fabric/configtx.yaml
        - ./e2e_cli/crypto-config.yaml:/etc/hyperledger/fabric/crypto-config.yaml
    depends_on:
      - orderer
      - peer0_org1
      - peer0_org2
    links:
      - orderer
      - peer0_org1
      - peer0_org2
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: bash -c 'while true; do sleep 20170504; done'

#networks:
#  default:
#    external:
#      name: hyperledger_fabric
